In [1]:
import BPt as bp
import numpy as np
import os
from os.path import dirname, abspath

/home/sage/anaconda3/envs/bpt/lib/python3.9/site-packages/nilearn/datasets/__init__.py:93: FutureWarning: Fetchers from the nilearn.datasets module will be updated in version 0.9 to return python strings instead of bytes and Pandas dataframes instead of Numpy arrays.
  warn("Fetchers from the nilearn.datasets module will be "

In [2]:
# Useful directories
main_dr = dirname(abspath(os.getcwd()))
data_dr = os.path.join(main_dr, 'data')

data = bp.read_pickle(os.path.join(data_dr, 'datasets', 'fs_thick_network.dataset'))
data

                 BMI  IST_intelligence_total    age sex education_level  \
participant_id
sub-0001        23.0                   159.0  22.00   0               2
sub-0002        20.0                   199.0  21.75   0               2
sub-0003        31.0                   227.0  25.25   0               0
sub-0004        20.0                   270.0  22.50   0               0
sub-0005        23.0                   212.0  22.25   1               0
...              ...                     ...    ...  ..             ...
sub-0924        21.0                   246.0  22.25   1               2
sub-0925        30.0                   150.0  25.25   1               2
sub-0926        22.0                   161.0  20.75   1               0
sub-0927        35.0                   190.0  24.25   0               2
sub-0928        19.0                   243.0  20.50   1               0

                thick_network_edges
participant_id
sub-0001                      556.0
sub-0002                      808.0
sub-0003                      283.0
sub-0004                      820.0
sub-0005                      312.0
...                             ...
sub-0924                      815.0
sub-0925                      444.0
sub-0926                      555.0
sub-0927                      463.0
sub-0928                      846.0

[927 rows x 6 columns]

In [ ]:
# Define re-usable problem spec
ps = bp.ProblemSpec(target='IST_intelligence_total', n_jobs=8)

In [ ]:
data.plot(['age'])

In [ ]:
from BPt.default.pipelines import compare_pipe

# Pipeline is just identity + pre-defined comparison pipeline
loader = bp.Loader('identity')
pipe = bp.Pipeline([loader, compare_pipe])

# Evaluate & print summary
results = bp.evaluate(pipe, data, ps)
results.summary()

In [ ]:
results.summary()